version: '3'

services:

  # app:
  #   image: myapp
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #      - db
  #   command: npm start

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: node_db
    ports:
      - "5432:5432"